[package]
name = "tequila-state"
version = "0.1.3"
edition = "2021"

[dependencies]
gstd.workspace = true
gmeta = { workspace = true, features = ["codegen"] }
tequila-io.workspace = true
scale-info.workspace = true
parity-scale-codec.workspace = true

[build-dependencies]
gear-wasm-builder = { workspace = true, features = ["metawasm"] }

[features]
binary-vendor = []
