[package]
name = "tequila-train"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
tequila-io.workspace = true
gstd.workspace = true
gmeta.workspace = true
hashbrown.workspace = true

[build-dependencies]
tequila-io.workspace = true
gear-wasm-builder.workspace = true
gmeta.workspace = true

[dev-dependencies]
gstd = { workspace = true, features = ["debug"] }
tequila-state.workspace = true
gtest.workspace = true

[features]
binary-vendor = ["tequila-state/binary-vendor"]

[workspace]
members = ["state"]

[workspace.package]
version = "0.1.4"
edition = "2021"
license = "MIT"
authors = ["Gear Technologies"]

[workspace.dependencies]
tequila-io = { path = "io" }
tequila-state = { path = "state" }
gstd = { git = "https://github.com/gear-tech/gear", rev = "946ac47" }
gmeta = { git = "https://github.com/gear-tech/gear", rev = "946ac47" }
gtest = { git = "https://github.com/gear-tech/gear", rev = "946ac47" }
gear-wasm-builder = { git = "https://github.com/gear-tech/gear", rev = "946ac47" }
hashbrown = "0.13"
scale-info = { version = "2", default-features = false }
parity-scale-codec = { version = "3", default-features = false }
enum-iterator = "1.4"
