[package]
name = "tequila-io"
version = "0.1.4"
edition = "2021"

[dependencies]
gmeta.workspace = true
gstd.workspace = true
scale-info.workspace = true
parity-scale-codec.workspace = true
enum-iterator.workspace = true
