name: Frontend PR

on:
  pull_request:
    branches: [master]
    paths:
      - frontend/**

env:
  CI: false

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install yarn
        run: sudo npm i yarn -g

      - name: Build
        run: |
          make init-frontend
          make frontend
